// Sample orders data
export const ordersData = [
  {
    id: '1',
    orderId: '25426',
    date: '11 Oct, 2025',
    total: '200.00',
    payment: 'Paid',
    items: '2 items',
    customerName: 'Kavin',
    status: 'Completed',
  },
  {
    id: '2',
    orderId: '25427',
    date: '11 Oct, 2025',
    total: '200.00',
    payment: 'Pending',
    items: '2 items',
    customerName: 'Kavin',
    status: 'Completed',
  },
  {
    id: '3',
    orderId: '25428',
    date: '11 Oct, 2025',
    total: '200.00',
    payment: 'Pending',
    items: '2 items',
    customerName: 'Kavin',
    status: 'Completed',
  },
  {
    id: '4',
    orderId: '25429',
    date: '11 Oct, 2025',
    total: '200.00',
    payment: 'Failed',
    items: '2 items',
    customerName: 'Kavin',
    status: 'Canceled',
  },
  {
    id: '5',
    orderId: '25430',
    date: '11 Oct, 2025',
    total: '200.00',
    payment: 'Refunded',
    items: '2 items',
    customerName: 'Kavin',
    status: 'Canceled',
  },
  {
    id: '6',
    orderId: '25431',
    date: '11 Oct, 2025',
    total: '200.00',
    payment: 'Paid',
    items: '2 items',
    customerName: 'Kavin',
    status: 'Processing',
  },
  {
    id: '7',
    orderId: '25432',
    date: '10 Oct, 2025',
    total: '200.00',
    payment: 'Paid',
    items: '2 items',
    customerName: 'Kavin',
    status: 'Processing',
  },
  {
    id: '8',
    orderId: '25433',
    date: '10 Oct, 2025',
    total: '200.00',
    payment: 'Paid',
    items: '2 items',
    customerName: 'Kavin',
    status: 'Processing',
  },
  {
    id: '9',
    orderId: '25434',
    date: '10 Oct, 2025',
    total: '200.00',
    payment: 'Paid',
    items: '2 items',
    customerName: 'Kavin',
    status: 'Processing',
  },
  {
    id: '10',
    orderId: '25435',
    date: '10 Oct, 2025',
    total: '200.00',
    payment: 'Paid',
    items: '2 items',
    customerName: 'Kavin',
    status: 'Processing',
  },
  {
    id: '11',
    orderId: '25436',
    date: '09 Oct, 2025',
    total: '150.00',
    payment: 'Paid',
    items: '3 items',
    customerName: 'Sarah',
    status: 'Completed',
  },
  {
    id: '12',
    orderId: '25437',
    date: '09 Oct, 2025',
    total: '350.00',
    payment: 'Pending',
    items: '5 items',
    customerName: 'John',
    status: 'Processing',
  },
  {
    id: '13',
    orderId: '25438',
    date: '08 Oct, 2025',
    total: '120.00',
    payment: 'Paid',
    items: '1 items',
    customerName: 'Alice',
    status: 'Completed',
  },
  {
    id: '14',
    orderId: '25439',
    date: '08 Oct, 2025',
    total: '280.00',
    payment: 'Failed',
    items: '4 items',
    customerName: 'Bob',
    status: 'Canceled',
  },
  {
    id: '15',
    orderId: '25440',
    date: '07 Oct, 2025',
    total: '190.00',
    payment: 'Paid',
    items: '2 items',
    customerName: 'Emma',
    status: 'Processing',
  },
];