// dashboardProducts.js - Mock data for products
export const dashboardProducts = [
  {
    id: '1',
    name: 'Lorem Ipsum',
    category: 'Plastic',
    price: 110.40,
    description: 'Lorem Ipsum is placeholder text commonly used in the graphic.',
    sales: 1269,
    remainingProducts: 1269,
  },
  {
    id: '2',
    name: 'Product Alpha',
    category: 'Metal',
    price: 89.99,
    description: 'High-quality metal product for industrial use.',
    sales: 856,
    remainingProducts: 543,
  },
  {
    id: '3',
    name: 'Beta Item',
    category: 'Wood',
    price: 125.50,
    description: 'Handcrafted wooden item with premium finish.',
    sales: 2134,
    remainingProducts: 892,
  },
  {
    id: '4',
    name: 'Gamma Product',
    category: 'Plastic',
    price: 67.25,
    description: 'Eco-friendly plastic product for everyday use.',
    sales: 1543,
    remainingProducts: 1205,
  },
  {
    id: '5',
    name: 'Delta Widget',
    category: 'Glass',
    price: 199.99,
    description: 'Premium glass widget with modern design.',
    sales: 687,
    remainingProducts: 234,
  },
  {
    id: '6',
    name: 'Epsilon Tool',
    category: 'Metal',
    price: 45.00,
    description: 'Durable metal tool for professional use.',
    sales: 3421,
    remainingProducts: 1876,
  },
  {
    id: '7',
    name: 'Zeta Device',
    category: 'Electronic',
    price: 299.99,
    description: 'Smart electronic device with AI features.',
    sales: 945,
    remainingProducts: 412,
  },
  {
    id: '8',
    name: 'Eta Component',
    category: 'Plastic',
    price: 34.50,
    description: 'Versatile plastic component for various applications.',
    sales: 2876,
    remainingProducts: 1543,
  },
  {
    id: '9',
    name: 'Theta Accessory',
    category: 'Fabric',
    price: 78.00,
    description: 'Premium fabric accessory with elegant design.',
    sales: 1234,
    remainingProducts: 765,
  },
  {
    id: '10',
    name: 'Iota Gadget',
    category: 'Electronic',
    price: 156.75,
    description: 'Innovative gadget with cutting-edge technology.',
    sales: 1098,
    remainingProducts: 543,
  },
  {
    id: '11',
    name: 'Kappa Module',
    category: 'Metal',
    price: 210.00,
    description: 'Industrial-grade metal module for heavy-duty use.',
    sales: 456,
    remainingProducts: 234,
  },
  {
    id: '12',
    name: 'Lambda Unit',
    category: 'Plastic',
    price: 92.50,
    description: 'Lightweight plastic unit with ergonomic design.',
    sales: 1876,
    remainingProducts: 923,
  },
  {
    id: '13',
    name: 'Mu Instrument',
    category: 'Wood',
    price: 345.00,
    description: 'Handcrafted wooden instrument with superior quality.',
    sales: 567,
    remainingProducts: 178,
  },
  {
    id: '14',
    name: 'Nu Equipment',
    category: 'Metal',
    price: 189.99,
    description: 'Professional-grade equipment for various tasks.',
    sales: 2345,
    remainingProducts: 1432,
  },
  {
    id: '15',
    name: 'Xi Apparatus',
    category: 'Glass',
    price: 267.50,
    description: 'Elegant glass apparatus with modern aesthetics.',
    sales: 789,
    remainingProducts: 345,
  },
  {
    id: '16',
    name: 'Omicron Part',
    category: 'Plastic',
    price: 54.25,
    description: 'Essential plastic part for assembly projects.',
    sales: 3210,
    remainingProducts: 1987,
  },
  {
    id: '17',
    name: 'Pi Solution',
    category: 'Electronic',
    price: 425.00,
    description: 'Advanced electronic solution for smart homes.',
    sales: 432,
    remainingProducts: 167,
  },
  {
    id: '18',
    name: 'Rho System',
    category: 'Metal',
    price: 178.00,
    description: 'Robust metal system for industrial applications.',
    sales: 1654,
    remainingProducts: 876,
  },
  {
    id: '19',
    name: 'Sigma Product',
    category: 'Wood',
    price: 134.99,
    description: 'Premium wooden product with natural finish.',
    sales: 987,
    remainingProducts: 543,
  },
  {
    id: '20',
    name: 'Tau Component',
    category: 'Plastic',
    price: 76.50,
    description: 'Durable plastic component for long-term use.',
    sales: 2543,
    remainingProducts: 1234,
  },
  {
    id: '21',
    name: 'Upsilon Device',
    category: 'Electronic',
    price: 312.00,
    description: 'State-of-the-art device with wireless connectivity.',
    sales: 765,
    remainingProducts: 298,
  },
  {
    id: '22',
    name: 'Phi Widget',
    category: 'Glass',
    price: 145.75,
    description: 'Decorative glass widget with artistic design.',
    sales: 1432,
    remainingProducts: 687,
  },
  {
    id: '23',
    name: 'Chi Tool',
    category: 'Metal',
    price: 98.00,
    description: 'Precision metal tool for specialized work.',
    sales: 2198,
    remainingProducts: 1345,
  },
  {
    id: '24',
    name: 'Psi Accessory',
    category: 'Fabric',
    price: 67.99,
    description: 'Stylish fabric accessory for modern lifestyle.',
    sales: 1567,
    remainingProducts: 834,
  },
  {
    id: '25',
    name: 'Omega Item',
    category: 'Plastic',
    price: 110.40,
    description: 'Versatile plastic item for everyday needs.',
    sales: 1890,
    remainingProducts: 956,
  },
];