import product1 from "../assets/images/product1.jpg";
import product2 from "../assets/images/product2.jpg";
import product3 from "../assets/images/product3.jpg";

export const products = [
  {
    id: 1,
    image: product1,
    name: "Plastic Chair",
    category: "highsale",
    price: 14.99,
    rating: 4.5,
    flag: "sale",
    tags: ["sale", "high-sale", "plastic"],
  },
  {
    id: 2,
    image: product2,
    name: "Plastic Chair",
    category: "highsale",
    price: 14.99,
    rating: 4.5,
    flag: "sale",
    tags: ["sale", "plastic", "discounts"],
  },
  {
    id: 3,
    image: product3,
    name: "Plastic Chair",
    price: 14.99,
    category: "safe",
    rating: 4.5,
    flag: "sale",
    tags: ["safe", "plastic", "eco"],
  },
  {
    id: 4,
    image: product1,
    name: "Plastic Chair",
    price: 14.99,
    category: "lowcost",
    rating: 4.5,
    flag: "out of stock",
    tags: ["low-cost", "plastic"],
  },
  {
    id: 10,
    image: product1,
    name: "Plastic Chair",
    category: "highsale",
    price: 14.99,
    rating: 4.5,
    flag: "sale",
    tags: ["sale", "high-sale", "plastic"],
  },
  {
    id: 20,
    image: product2,
    name: "Plastic Chair",
    category: "highsale",
    price: 14.99,
    rating: 4.5,
    flag: "sale",
    tags: ["sale", "discounts", "plastic"],
  },
  {
    id: 30,
    image: product3,
    name: "Plastic Chair",
    price: 14.99,
    category: "safe",
    rating: 4.5,
    flag: "sale",
    tags: ["eco", "safe", "sale"],
  },
  {
    id: 40,
    image: product1,
    name: "Plastic Chair",
    price: 14.99,
    category: "lowcost",
    rating: 4.5,
    flag: "out of stock",
    tags: ["low-cost", "plastic"],
  },
  {
    id: 5,
    image: product2,
    name: "Plastic Chair",
    price: 14.99,
    rating: 4.5,
    category: "danger",
    flag: "sale",
    tags: ["sale", "danger", "plastic"],
  },
  {
    id: 101,
    name: "Green Capsicum",
    price: 14.0,
    rating: 4.5,
    image: null,
    flag: null,
    category: "vegetables",
    tags: ["fresh", "organic", "vegetables"],
  },
  {
    id: 102,
    name: "Red Capsicum",
    price: 14.0,
    rating: 4.8,
    image: null,
    flag: "sale",
    category: "vegetables",
    tags: ["fresh", "organic", "sale"],
  },
  {
    id: 103,
    name: "Fresh Tomatoes",
    price: 8.5,
    rating: 4.2,
    image: null,
    flag: "best sale",
    category: "vegetables",
    tags: ["fresh", "local", "best-deal"],
  },
  {
    id: 104,
    name: "Organic Lettuce",
    price: 6.99,
    rating: 4.6,
    image: null,
    flag: null,
    category: "vegetables",
    tags: ["organic", "fresh", "healthy"],
  },
  {
    id: 105,
    name: "Sweet Potatoes",
    price: 12.0,
    rating: 4.4,
    image: null,
    flag: "out of stock",
    category: "vegetables",
    tags: ["organic", "nutritious", "low-stock"],
  },
  {
    id: 106,
    name: "Fresh Carrots",
    price: 9.99,
    rating: 4.7,
    image: null,
    flag: null,
    category: "vegetables",
    tags: ["fresh", "vitamin-rich", "organic"],
  },
  {
    id: 107,
    name: "Electronic Components",
    price: 45.0,
    rating: 3.2,
    image: null,
    flag: "sale",
    category: "electronics",
    tags: ["sale", "discounts", "electronics"],
  },
  {
    id: 108,
    name: "Textile Waste Bundle",
    price: 12.99,
    rating: 4.0,
    image: null,
    flag: null,
    category: "textiles",
    tags: ["low-cost", "recycled", "eco"],
  },
  {
    id: 109,
    name: "Paper Waste Package",
    price: 8.75,
    rating: 4.2,
    image: null,
    flag: "out of stock",
    category: "paper",
    tags: ["high-sale", "paper", "low-stock"],
  },
  {
    id: 110,
    name: "Glass Bottle Collection",
    price: 18.25,
    rating: 4.6,
    image: null,
    flag: null,
    category: "glass",
    tags: ["high-quality", "eco", "reusable"],
  },
  {
    id: 111,
    name: "Wood Scrap Bundle",
    price: 22.99,
    rating: 4.3,
    image: null,
    flag: null,
    category: "wood",
    tags: ["best-deal", "recycled", "wood"],
  },
  {
    id: 112,
    name: "Mixed Plastic Waste",
    price: 16.5,
    rating: 3.8,
    image: null,
    flag: null,
    category: "plastic",
    tags: ["emergencies", "eco", "plastic"],
  },
  {
    id: 113,
    name: "Steel Scrap Collection",
    price: 35.0,
    rating: 4.7,
    image: null,
    flag: "best sale",
    category: "metal",
    tags: ["high-quality", "newest", "metal"],
  },
  {
    id: 114,
    name: "Circuit Board Waste",
    price: 28.75,
    rating: 4.1,
    image: null,
    flag: null,
    category: "electronics",
    tags: ["high-sale", "electronics", "eco"],
  },
  {
    id: 115,
    name: "Fabric Waste Bundle",
    price: 11.25,
    rating: 3.9,
    image: null,
    flag: null,
    category: "textiles",
    tags: ["low-cost", "eco", "textiles"],
  },
  {
    id: 116,
    name: "Cardboard Collection",
    price: 7.99,
    rating: 4.4,
    image: null,
    flag: "sale",
    category: "paper",
    tags: ["best-deal", "sale", "recycled"],
  },
];
